[General]
  backend     = "gist"                                                                                                                           # specify backend service to sync snippets (gist, ghe or gitlab, default: gist)
  cmd         = ["sh", "-c"]                                                                                                                     # specify the command to execute the snippet with
  color       = false                                                                                                                            # enables output coloring with fzf, same as '--color' flag
  column      = 40                                                                                                                               # column size for list command
  editor      = "nvim"                                                                                                                           # your favorite text editor
  format      = "[$description]: $command $tags"                                                                                                 # controls the format of the output when searching
  selectcmd   = "fzf --ansi --layout=reverse --border --height=90% --cycle --prompt='Snippets: ' --preview 'echo {}' --preview-window=right:80%"
  snippetdirs = ["~/.config/pet/snippets"]                                                                                                       # all separated files snippets
  snippetfile = "~/.config/pet/snippet-general.toml"                                                                                             # specify snippet directory
  sortby      = "description"                                                                                                                    # specify how snippets get sorted (recency (default), -recency, description, -description, command, -command, output, -output)

[Gist]
  access_token = ""                 # your access token
  auto_sync    = false              # sync automatically when editing snippets
  file_name    = "pet-snippet.toml" # specify gist file name
  gist_id      = ""                 # Gist ID
  public       = false              # public or priate

[GitLab]
  access_token = "XXXXXXXXXXXXX"    # your access token
  auto_sync    = false              # sync automatically when editing snippets
  file_name    = "pet-snippet.toml" # specify GitLab Snippets file name
  id           = ""                 # GitLab Snippets ID
  visibility   = "private"          # public or internal or private
