name = "kanagawa-dragon"
author = "chianyung"
description = "Kanagawa Dragon dark theme"

[colors]
file = { r = 197, g = 201, b = 197 }
directory = { r = 139, g = 164, b = 176 }
symlink = { r = 142, g = 164, b = 162 }
executable = { r = 138, g = 154, b = 123 }
size = { r = 142, g = 164, b = 162 }
date = { r = 115, g = 124, b = 115 }
user = { r = 200, g = 192, b = 147 }
group = { r = 114, g = 113, b = 105 }
permission_dir = { r = 196, g = 178, b = 138 }
permission_read = { r = 138, g = 154, b = 123 }
permission_write = { r = 196, g = 178, b = 138 }
permission_exec = { r = 138, g = 154, b = 123 }
permission_none = { r = 98, g = 94, b = 90 }

[special_files]

[special_files.folders]
".git" = { r = 195, g = 64, b = 67 }
"node_modules" = { r = 114, g = 113, b = 105 }
"target" = { r = 114, g = 113, b = 105 }
"dist" = { r = 114, g = 113, b = 105 }

[special_files.exact_match]
"README.md" = { r = 230, g = 195, b = 132 }
"Cargo.toml" = { r = 122, g = 168, b = 159 }

[extensions.colors]
md = { r = 230, g = 195, b = 132 }
toml = { r = 122, g = 168, b = 159 }
yaml = { r = 122, g = 168, b = 159 }
yml = { r = 122, g = 168, b = 159 }
json = { r = 255, g = 160, b = 102 }
rs = { r = 126, g = 156, b = 216 }
go = { r = 122, g = 168, b = 159 }
lua = { r = 149, g = 127, b = 184 }
