###############################################################################
#                          Kanagawa Dragon Theme                             #
###############################################################################

code_syntax_highlight = "kanagawa-dragon"
full_screen_fg = "#c5c9c5"
full_screen_bg = "#181616"
gradient_color = ["#c4b28a", "#8ea4a2"]
directory_icon_color = "#8ba4b0"
file_panel_fg = "#c5c9c5"
file_panel_bg = "#181616"
file_panel_border = "#393836"
file_panel_border_active = "#c4b28a"
file_panel_top_directory_icon = "#8ea4a2"
file_panel_top_path = "#b6927b"
file_panel_item_selected_fg = "#c5c9c5"
file_panel_item_selected_bg = "#223249"
footer_fg = "#C8C093"
footer_bg = "#0d0c0c"
footer_border = "#393836"
footer_border_active = "#8ea4a2"
sidebar_fg = "#C8C093"
sidebar_bg = "#0d0c0c"
sidebar_title = "#c4b28a"
sidebar_border = "#393836"
sidebar_border_active = "#8ea4a2"
sidebar_item_selected_fg = "#c5c9c5"
sidebar_item_selected_bg = "#223249"
sidebar_divider = "#658594"
modal_fg = "#c5c9c5"
modal_bg = "#0d0c0c"
modal_border_active = "#c4b28a"
modal_cancel_fg = "#181616"
modal_cancel_bg = "#E82424"
modal_confirm_fg = "#181616"
modal_confirm_bg = "#8a9a7b"
help_menu_hotkey = "#8ea4a2"
help_menu_title = "#c4b28a"
cursor = "#8ea4a2"
correct = "#8a9a7b"
error = "#E82424"
hint = "#b6927b"
cancel = "#c4746e"
