## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Catppuccin Mocha
# Scheme author: https://github.com/catppuccin/catppuccin
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)

"bookmark"                       = { fg = "#f5c2e7" }
"border"                         = { fg = "#45475a" }
"branch"                         = { fg = "#89dceb" }
"change"                         = { fg = "#eba0ac" }
"commit"                         = { fg = "#a6e3a1" }
"completion"                     = { fg = "#cdd6f4" }
"completion selected"            = { bold = true }
"confirmation"                   = { bg = "#1e1e2e" }
"confirmation border"            = { fg = "#eba0ac", bold = true }
"confirmation dimmed"            = { fg = "#45475a" }
"confirmation selected"          = { bg = "#313244", fg = "#cdd6f4" }
"confirmation text"              = { fg = "#89b4fa", bold = true }
"details"                        = { fg = "#cdd6f4" }
"details selected"               = { bold = true }
"dimmed"                         = { fg = "#45475a", bg = "#1e1e2e" }
"error"                          = { fg = "#eba0ac", bold = true }
"evolog"                         = { fg = "#cdd6f4" }
"evolog selected"                = { bg = "#313244", fg = "#cdd6f4", bold = true }
"file"                           = { fg = "#f5e0dc" }
"help"                           = { bg = "#1e1e2e" }
"help border"                    = { fg = "#181825" }
"help title"                     = { fg = "#a6e3a1", bold = true, underline = true }
"matched"                        = { fg = "#f5e0dc" }
"menu"                           = { bg = "#1e1e2e" }
"menu border"                    = { fg = "#181825" }
"menu dimmed"                    = { fg = "#45475a" }
"menu matched"                   = { fg = "#f5e0dc", bold = true }
"menu selected"                  = { bg = "#313244", fg = "#cdd6f4" }
"menu shortcut"                  = { fg = "#f5c2e7" }
"menu title"                     = { fg = "#1e1e2e", bg = "#f5c2e7", bold = true }
"oplog selected"                 = { bold = true }
"preview"                        = { fg = "#cdd6f4" }
"preview border"                 = { fg = "#181825" }
"rebase"                         = { bold = true }
"revisions"                      = { fg = "#cdd6f4" }
"revisions details selected"     = { bg = "#313244" }
"revisions dimmed"               = { fg = "#45475a" }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"revisions selected"             = { bg = "#181825" }
"revset completion dimmed"       = { fg = "#45475a" }
"revset completion matched"      = { fg = "#f5e0dc", bold = true }
"revset completion selected"     = { bg = "#313244", fg = "#cdd6f4" }
"revset completion text"         = { fg = "#cdd6f4" }
"revset text"                    = { fg = "#cdd6f4", bold = true }
"revset title"                   = { fg = "#89b4fa", bold = true }
"selected"                       = { bg = "#181825", fg = "#cdd6f4", bold = true }
"shortcut"                       = { fg = "#cba6f7" }
"source_marker"                  = { bg = "#181825", fg = "#1e1e2e", bold = true }
"status"                         = { bg = "#181825" }
"status dimmed"                  = { fg = "#45475a" }
"status shortcut"                = { fg = "#f5c2e7" }
"status title"                   = { fg = "#1e1e2e", bg = "#74c7ec", bold = true }
"success"                        = { fg = "#a6e3a1", bold = true }
"target_marker"                  = { bg = "#11111b", fg = "#1e1e2e", bold = true }
"text"                           = { fg = "#cdd6f4", bg = "#1e1e2e" }
"title"                          = { fg = "#89b4fa", bold = true }
"undo"                           = { bg = "#1e1e2e" }
"undo confirmation dimmed"       = { fg = "#45475a" }
"undo confirmation selected"     = { bg = "#313244", fg = "#cdd6f4" }
"workspace"                      = { fg = "#74c7ec" }
