[metadata]
name = "xgit-reflogs"
description = "Browse Git reflog entries"
requirements = ["git"]

[source]
command = "git reflog --format='%gD%x09%C(yellow)%h%C(auto) %gs%C(reset)' 2>/dev/null"
ansi = true

frecency = false
output = "{strip_ansi|split:\\t:0}"

[preview]
command = "DFT_COLOR=always git show --ext-diff --color=always '{split:\\t:0}'"

[ui]
layout = "landscape"

[ui.preview_panel]
size = 65
