[accounts.personal]
  git_email       = "cnytechcode@gmail.com"
  git_name        = "chianyungcode"
  github_token    = "cny_gh_pat"
  github_username = "chianyungcode"
  signing_key     = "signing_key_cny"

[accounts.secondary]
  git_email       = "seraphyne31@gmail.com"
  git_name        = "seraphynee"
  github_token    = "spy_gh_pat"
  github_username = "seraphynee"
  signing_key     = "signing_key_spy"

[accounts.server-minimal]
  git_email       = "chianyungcode-server@local.invalid"
  git_name        = "chianyungcode-server"
  github_token    = ""
  github_username = ""
  signing_key     = ""
