[directories]
  repos_dir    = "${HOME}/repos"
  ssh_keys_dir = "${HOME}/.ssh_keys"
  user_bin_dir = "${HOME}/bin"

[theme.vesper]
  background    = "#101010"
  surface       = "#161616"
  input         = "#1C1C1C"
  selection     = "#232323"
  border        = "#282828"
  scrollbar     = "#343434"
  foreground    = "#FFFFFF"
  muted         = "#A0A0A0"
  dim           = "#7E7E7E"
  faint         = "#505050"
  orange        = "#FFC799"
  orange_bright = "#FFCFA8"
  mint          = "#99FFE4"
  error         = "#FF8080"
  warning       = "#FF7300"
  separator     = "#65737E"

[theme.kanagawa_dragon]
  background    = "#181616"
  surface       = "#0d0c0c"
  input         = "#1D1C19"
  selection     = "#223249"
  border        = "#393836"
  scrollbar     = "#625e5a"
  foreground    = "#c5c9c5"
  muted         = "#C8C093"
  dim           = "#737c73"
  faint         = "#625e5a"
  blue          = "#8ba4b0"
  blue_bright   = "#7FB4CA"
  green         = "#8a9a7b"
  green_bright  = "#87a987"
  red           = "#c4746e"
  error         = "#E82424"
  yellow        = "#c4b28a"
  warning       = "#FF9E3B"
  violet        = "#8992a7"
  orange        = "#b6927b"
  aqua          = "#8ea4a2"
  separator     = "#658594"
