[directories]
  repos_dir    = "${HOME}/repos"
  ssh_keys_dir = "${HOME}/.ssh_keys"
  user_bin_dir = "${HOME}/bin"

[theme.vesper]
  background    = "#101010"
  surface       = "#161616"
  input         = "#1C1C1C"
  selection     = "#232323"
  border        = "#282828"
  scrollbar     = "#343434"
  foreground    = "#FFFFFF"
  muted         = "#A0A0A0"
  dim           = "#7E7E7E"
  faint         = "#505050"
  orange        = "#FFC799"
  orange_bright = "#FFCFA8"
  mint          = "#99FFE4"
  error         = "#FF8080"
  warning       = "#FF7300"
  separator     = "#65737E"

[theme.kanagawa_dragon]
  background    = "#1F1F28"
  surface       = "#16161D"
  input         = "#2A2A37"
  selection     = "#2D4F67"
  border        = "#363646"
  scrollbar     = "#54546D"
  foreground    = "#DCD7BA"
  muted         = "#C8C093"
  dim           = "#727169"
  faint         = "#54546D"
  blue          = "#7E9CD8"
  blue_bright   = "#7FB4CA"
  green         = "#98BB6C"
  red           = "#C34043"
  error         = "#E82424"
  yellow        = "#E6C384"
  warning       = "#FF9E3B"
  violet        = "#957FB8"
  orange        = "#FFA066"
  aqua          = "#7AA89F"
  separator     = "#658594"
