[directories]
  repos_dir    = "${HOME}/repos"
  ssh_keys_dir = "${HOME}/.ssh_keys"
  user_bin_dir = "${HOME}/bin"

[theme.vesper]
  background    = "#101010"
  surface       = "#161616"
  input         = "#1C1C1C"
  selection     = "#232323"
  border        = "#282828"
  scrollbar     = "#343434"
  foreground    = "#FFFFFF"
  muted         = "#A0A0A0"
  dim           = "#7E7E7E"
  faint         = "#505050"
  orange        = "#FFC799"
  orange_bright = "#FFCFA8"
  mint          = "#99FFE4"
  error         = "#FF8080"
  warning       = "#FF7300"
  separator     = "#65737E"
