# This data file is for .chezmoiexternal/ directory
# macOS application that unavailable on homebrew or mas, so needed to install from the download url from their website
# options for field type : dmg | zip

[[macos_external_app]]
  app_name     = "wisprflow"
  download_url = "https://dl.wisprflow.ai/mac-apple/latest"
  type         = "dmg"

[[macos_external_app]]
  app_name     = "recordly"
  download_url = "https://github.com/webadderall/Recordly/releases/latest/download/Recordly-arm64.dmg"
  type         = "dmg"

  # [[macos_external_app]]
  #   app_name     = "tuna"
  #   download_url = "https://tunaformac.com/download/latest"
  #   type         = "dmg"
  #
  # # blur external 
  # [[macos_external_app]]
  #   app_name     = "monocle"
  #   download_url = "https://files.heyiam.dk/updates/Monocle-3-0-3.dmg"
  #   type         = "dmg"
  #
  # # live wallpaper
  # [[macos_external_app]]
  #   app_name     = "shakkei"
  #   download_url = "https://downloads.shakkei.app/Shakkei.dmg"
  #   type         = "dmg"

  # tidy up your dock
  # [[macos_external_app]]
  #   app_name     = "modokki"
  #   download_url = "https://modoki.app/download"
  #   type         = "dmg"
