# This data file is for .chezmoiexternal/ directory
# macOS application that unavailable on homebrew or mas, so needed to install from the download url from their website
# options for field type : dmg | zip

[[macos_external_app]]
  app_name     = "wisprflow"
  download_url = "https://dl.wisprflow.ai/mac-apple/latest"
  type         = "dmg"
