# macOS application that unavailable on homebrew or mas
# options for field type : dmg | zip

[[macos_external_app]]
app_name = "wisprflow"
download_url = "https://dl.wisprflow.ai/mac-apple/latest"
type = "dmg"
