[packages]
  [packages.homebrew]
  to_remove = ["htop"]
    [packages.homebrew.common]
    # packages that needed in every computer
    taps = [
      "arl/arl",
      "chase/tap",
      "dopplerhq/cli",
      "dotenvx/brew",
      "felixkratz/formulae",
      "grishka/grishka",
      "homebrew/bundle",
      "homebrew/services",
      "jesseduffield/lazydocker",
      "jesseduffield/lazygit",
      "jstkdng/programs",
      "knqyf263/pet",
      "koekeishiya/formulae",
      "koyeb/tap",
      "nikitabobko/tap",
      "olets/tap",
      "osx-cross/arm",
      "osx-cross/avr",
      "pablopunk/brew",
      "pkgxdev/made",
      "qmk/qmk",
      "skiptools/skip",
      "stripe/stripe-cli",
      "supabase/tap",
      "teamookla/speedtest",
      "vladkens/tap",
      "waydabber/betterdisplay",
      "withgraphite/tap",
    ]
    casks = [
      "1password-cli",
      "android-platform-tools",
      "fig",
      "git-credential-manager",
      "skip",
      "termius",
    ]
    formulae = [
      "vivid",
      "most",
      "gping",
      "btop",
      "xz",
      "atuin",
      "icu4c@76",
      "awscli",
      "bat",
      "berkeley-db",
      "bfg",
      "brew-gem",
      "chezmoi",
      "cliclick",
      "ruby",
      "cocoapods",
      "direnv",
      "dotter",
      "eza",
      "fastfetch",
      "fd",
      "ffmpegthumbnailer",
      "fish",
      "flyctl",
      "node",
      "fx",
      "fzf",
      "gh",
      "git",
      "git-delta",
      "git-filter-repo",
      "git-lfs",
      "glow",
      "gnupg",
      "gzip",
      "helix",
      "httpie",
      "hub",
      "hyperfine",
      "imagemagick",
      "jq",
      "libfido2",
      "luarocks",
      "mongosh",
      "navi",
      "neonctl",
      "neovim",
      "nushell",
      "nvm",
      "openssh",
      "pkgconf",
      "pngpaste",
      "poppler",
      "presenterm",
      "pueue",
      "python@3.11",
      "ripgrep",
      "sesh",
      "speedtest-cli",
      "sshs",
      "starship",
      "stow",
      "taplo",
      "television",
      "tlrc",
      "tmux",
      "tmuxinator",
      "tmuxp",
      "unzip",
      "vim",
      "watchman",
      "wget",
      "wtfutil",
      "yazi",
      "yq",
      "yubico-piv-tool",
      "zoxide",
      "arl/arl/gitmux",
      "dopplerhq/cli/doppler",
      "dotenvx/brew/dotenvx",
      "felixkratz/formulae/borders",
      "jesseduffield/lazydocker/lazydocker",
      "jesseduffield/lazygit/lazygit",
      "knqyf263/pet/pet",
      "koyeb/tap/koyeb",
      "qmk/qmk/qmk",
      "stripe/stripe-cli/stripe",
      "supabase/tap/supabase",
      "teamookla/speedtest/speedtest",
      "vladkens/tap/macmon",
      "waydabber/betterdisplay/betterdisplaycli",
      "withgraphite/tap/graphite",
    ]
    # TODO: Separate taps,casks,formulae into dev_computer
    [packages.homebrew.dev_computer]
    # packages that needed in development computes
    taps = []
    casks = []
    formulae = []

    # TODO: Separate taps,casks,formulae into personal_computer
    [packages.homebrew.personal_computer]
    # packages that needed for utility in that computer
    taps = []
    casks = []
    formulae = []

  [packages.apt]
    [packages.apt.common]
    packages = [
      "apt-transport-https",
      "bat",                 # cat with syntax highlighting and Git integration
      "curl",
      "dnsutils",
      "fd-find",
      "figlet",
      "fzf",
      "git",
      "git-extras",
      "gnupg",
      "gpg",
      "jq",
      "logrotate",
      "lolcat",
      "mc",                  # Midnight Commander
      "nano",
      "ncdu",                # NCurses Disk Usage
      "needrestart",
      "net-tools",
      "openssh-server",
      "p7zip-full",
      "ripgrep",             # search tool like grep and the silver searcher
      "sudo",
      "tzdata",
      "unzip",
      "wget",
      "zsh",
    ]
    [packages.apt.dev_computer]
    packages = []
    [packages.apt.homelab_member]
    packages = ["iperf"]
    [packages.apt.personal_computer]
    packages = []

  [packages.pacman]
    [packages.pacman.common]
    packages = [
      "base-devel",  # Equivalent to apt-transport-https and build essentials
      "bat",         # cat with syntax highlighting and Git integration
      "curl",
      "bind-tools",  # Equivalent to dnsutils
      "fd",          # Equivalent to fd-find
      "figlet",
      "fzf",
      "git",
      "git-extras",
      "gnupg",
      "gpg",
      "jq",
      "logrotate",
      "lolcat",
      "mc",          # Midnight Commander
      "nano",
      "ncdu",        # NCurses Disk Usage
      "needrestart",
      "net-tools",
      "openssh",     # Equivalent to openssh-server
      "p7zip",       # Equivalent to p7zip-full
      "ripgrep",     # search tool like grep and the silver searcher
      "sudo",
      "tzdata",
      "unzip",
      "wget",
      "zsh",
    ]
    [packages.pacman.dev_computer]
    packages = []
    [packages.pacman.homelab_member]
    packages = ["iperf"]
    [packages.pacman.personal_computer]
    packages = []
