[packages]
  [packages.homebrew]
    to_remove = ["htop"]
    [packages.homebrew.common]
      # packages that needed in every computer
      taps = [
        "arl/arl",                  # Taps for gitmux
        "chase/tap",
        "dopplerhq/cli",
        "dotenvx/brew",
        "felixkratz/formulae",
        "grishka/grishka",
        "homebrew/bundle",
        "homebrew/services",
        "jesseduffield/lazydocker",
        "jesseduffield/lazygit",
        "jstkdng/programs",
        "knqyf263/pet",
        "koekeishiya/formulae",
        "koyeb/tap",
        "nikitabobko/tap",
        "olets/tap",
        "osx-cross/arm",
        "osx-cross/avr",
        "pablopunk/brew",
        "pkgxdev/made",
        "qmk/qmk",
        "skiptools/skip",
        "stripe/stripe-cli",
        "supabase/tap",
        "teamookla/speedtest",
        "vladkens/tap",
        "waydabber/betterdisplay",
        "withgraphite/tap",
      ]
      casks = [
        "1password",
        "1password-cli",
        "android-platform-tools",
        "git-credential-manager",
        "ghostty",
        "jordanbaird-ice",           # Menu bar customization
        "termius",
        "mocki-toki/formulae/barik",
        "orbstack",                  # Docker replacement
        "tailscale",
        "visual-studio-code",
      ]
      formulae = [
        "atuin", # Better shell history
        "bat",   # cat with syntax highlighting and git integration
        # "berkeley-db",               # Oracle berkeley-db
        "bfg", # Remove large files or passwords from Git history like git-filter-branch
        # "brew-gem",
        "btop",
        "chezmoi",
        # "cliclick",                  # macOS CLI tool for emulating mouse and keyboard events
        "cocoapods", # depedency manager for switft
        "coreutils", # GNU coreutils
        # "dotter", # dotfile manager and templater.
        "eza",                       # Better ls
        "fd",                        # Better find
        "findutils",                 # GNU find
        "fzf",                       # Fuzzy finder
        "gawk",                      # GNU awk
        "git",
        "gitleaks",                  # Find secrets that leaks in your repo
        "git-delta",                 # Git diff viewer or pager
        "gnu-getopt",
        "gnu-sed",                   # GNU implementation of the famous stream editor
        "gnu-tar",                   # GNU version of the tar archiving utility
        "gnutls",                    # GNU Transport Layer Security (TLS) Library
        "git-filter-repo",
        "git-lfs",
        "gnupg",                     # GPG
        "grep",                      # GNU grep
        "gping",                     # Ping with graph
        "gzip",                      # Popular GNU data compression program
        "halp",                      # Better help
        "icu4c@76",
        "imagemagick",               # Image processing
        "jq",                        # Lightweight and flexible command-line JSON processor
        "libfido2",                  # Provides library functionality for FIDO U2F & FIDO 2.0, including USB
        "most",                      # Pager
        "navi",                      # An interactive cheatsheet tool for the command-line
        "neonctl",                   # Neon CLI
        "neovim",                    # Text
        "openssh",                   # SSH
        "pkgconf",                   # package compiler and linker metadata toolkit
        "rip2",                      # A safer rm, written in Rust
        "ripgrep",                   # Search tool like grep and the silver searcher
        "ssh-copy-id",               # Add a public key to a remote machine's authorized_keys file
        "starship",                  # Configure shell prompt appearance
        "taplo",                     # TOML parser
        "tlrc",                      # TLDR client
        "tmux",                      # Terminal multiplexer
        "unzip",
        "vim",                       # Alternative neovim
        "vivid",                     # Better ls
        "watchman",                  # File watcher
        "wget",
        "whois",                     # Lookup tool for domain names and other internet resources
        "withgraphite/tap/graphite",
        "wtfutil",
        "xz",
        "yazi",                      # File manager in CLI
        "yq",                        # YAML processor
        "zoxide",                    # Better cd
      ]

    [packages.homebrew.dev_computer]
      taps = []
      casks = [
        "amazon-q",
        "apidog",
        "fork",     # "sourcetree", alternative to fork
        "datagrip",
        "cursor",
      ]
      formulae = [
        "act",                                 # runs GitHub Actions locally
        "awscli",
        "direnv",                              # Environment manager for shell based current working directory
        "dopplerhq/cli/doppler",               # Secret manager
        "dotenvx/brew/dotenvx",                # Env manager
        "fastfetch",                           # Better system info
        "ffmpegthumbnailer",                   # Video thumbnail for yazi cli
        "fish",                                # Alternative shell for zsh
        "flyctl",                              # Fly.io CLI
        "fx",                                  # Better grep
        "gh",                                  # Github CLI
        "git-delta",                           # Pager for git
        "git-extras",                          # Add extra command to default git
        "gitmux",                              # Git status bar in tmux
        "glab",                                # GitLab CLI
        "glow",                                # Render markdown in CLI
        "helix",                               # Alternative neovim
        "httpie",                              # HTTP client
        "hurl",                                # command line tool that runs HTTP requests defined in a simple plain text format.
        "hyperfine",                           # A command-line benchmarking tool
        "jesseduffield/lazydocker/lazydocker", # Docker manager
        "jesseduffield/lazygit/lazygit",
        "knqyf263/pet/pet",                    # CLI snippet manager
        "koyeb/tap/koyeb",                     # Koyeb CLI
        "luarocks",                            # Lua package manager
        "mongosh",                             # MongoDB shell
        "nushell",                             # Alternative shell
        "pngpaste",                            # Paste PNG into files on MacOS, much like pbpaste does for text.
        "poppler",                             # PDF rendering library
        "pueue",                               # Task runner and scheduler
        "sesh",                                # Tmux session manager
        "sshs",                                # Graphical command-line client for SSH
        "shellcheck",
        "stow",                                # Symlink manager
        "stripe/stripe-cli/stripe",
        "tectonic",                            # render LaTex math
        "tmuxinator",                          # Tmux session manager
        "tmuxp",                               # Tmux session manager
        "television",                          # Alternative to yazi
        "vladkens/tap/macmon",                 # Mac monitor
      ]

    [packages.homebrew.personal_computer]
      casks = [
        "nikitabobko/tap/aerospace",
        "anki",
        "arc",
        "apparency",                 # Showing detail app in finder
        "bettertouchtool",
        "blip",                      # Send any size file between devices
        "bunch",
        "capacities",                # Note taking
        "clop",                      # Image and video resizer
        "cloudmounter",              # Mounts cloud storages as local discs
        "cursor",                    # IDE : Write, edit, and chat about your code with AI
        "datagrip",                  # Databases and SQL IDE
        "discord",
        "dbngin",                    # Lightweight DB GUI, Database version management tool
        "dockdoor",
        "ogdesign-eagle",            # Organise all your reference images in one place
        "espanso",
        "folo",                      # Follow the organized information
        "google-chrome",
        "hazel",                     # File organize automation
        "hazeover",                  # dim your inactive window
        "homerow",                   # Keyboard shortcuts for every button on your screen
        "iina",
        # "kanata",             # Cross-platform software keyboard remapper for Linux, macOS and Windows
        "karabiner-elements",
        "kindavim",
        "keyboard-cowboy",    # Keyboard shortcut utility
        "leader-key",
        "linear-linear",      # App to manage software development and track bugs
        "lookaway",           # App for maintaining your eye rest
        "lulu",               # Firewall
        "lunar",              # Configure your display management
        "mediamate",          # UI replacement for volume, brightness and now playing controls
        "menuwhere",
        "moom",               # Manage saved layout window for better workflow
        "mouseless",
        "notion",
        "obsidian",
        "ollama",             # Run local LLM
        "qspace-pro",         # Better finder
        "raycast",
        "raindropio",
        "readdle-spark",      # Spark mail
        "rectangle",
        "remnote",
        "replacicon",         # Replace your app icon
        "swift-shift",        # Drag window with ctl + shift
        "transnomino",        # Batch rename utility
        "via",
        "vial",
        "warp",
        "wezterm",
        "zed",                # IDE
        "zen",                # Browser
      ]
      taps = []
      formulae = [
        "felixkratz/formulae/borders",
        "presenterm",                  # Presentation in CLI
        "yubico-piv-tool",             # Yubikey PIV tool
        "qmk/qmk/qmk",                 # QMK CLI
      ]

    [packages.homebrew.homelab_member]
      taps = []
      casks = ["arc"]
      formulae = ["ffmpeg", "iperf", "nmap", "tailspin"]


  [packages.mas]
    [packages.mas.common]
      apps = []
    [packages.mas.dev_computer]
      apps = []
    [packages.mas.homelab_member]
      apps = []
    [packages.mas.personal_computer]
      apps = [
        "6746757189", # Corner Time
        "1355679052", # Dropover
        "6698876601", # Folder preview
        "6739802604", # Folo
        "1502839586", # Hand mirror
        "6444667067", # Hyperduck
        "1609960918", # Jomo
        "6474854386", # Launchpallete
        "1551462255", # Mouseboost
        "6739781207", # Pieoneer
        "6451349778", # Rapidmg
        "1666327168", # Spaced
        "966085870",  # Ticktick
        "497799835",  # Velja
        "1516894961", # Codye
      ]

      # === APT PACKAGE MANAGER ===

  [packages.apt]
    to_remove = []
    [packages.apt.common]
      packages = [
        "apt-transport-https",
        "bat",                 # cat with syntax highlighting and Git integration
        "curl",
        "dnsutils",
        "fd-find",
        "figlet",
        "fzf",
        "git",
        "git-extras",
        "gnupg",
        "gpg",
        "jq",
        "logrotate",
        "lolcat",
        "mc",                  # Midnight Commander
        "nano",
        "ncdu",                # NCurses Disk Usage
        "needrestart",
        "net-tools",
        "openssh-server",
        "p7zip-full",
        "ripgrep",             # search tool like grep and the silver searcher
        "sudo",
        "tzdata",
        "unzip",
        "wget",
        "zsh",
      ]
    [packages.apt.dev_computer]
      packages = []
    [packages.apt.homelab_member]
      packages = ["iperf"]
    [packages.apt.personal_computer]
      packages = []

  [packages.pacman]
    [packages.pacman.common]
      packages = [
        "base-devel",    # Equivalent to apt-transport-https and build essentials
        "bat",           # cat with syntax highlighting and Git integration
        "curl",
        "bind-tools",    # Equivalent to dnsutils
        "fd",            # Equivalent to fd-find
        "figlet",
        "fzf",
        "git",
        "git-extras",
        "gnome-keyring", # For 1password two factor auth
        "gnupg",
        "jq",
        "logrotate",
        "lolcat",
        "mc",            # Midnight Commander
        "nano",
        "ncdu",          # NCurses Disk Usage
        "net-tools",
        "openssh",       # Equivalent to openssh-server
        "p7zip",         # Equivalent to p7zip-full
        "polkit-gnome",  # For 1password prompt available
        "ripgrep",       # search tool like grep and the silver searcher
        "sudo",
        "tzdata",
        "unzip",
        "wget",
        "zsh",
      ]
    [packages.pacman.dev_computer]
      packages = [
        "dpkg",
        "pueue",           # Task runner and scheduler
        "starship",
        "github-cli",      # Github CLI
        "git-delta",       # Pager for git
        "git-extras",      # Add extra command to default git
        "glab",            # GitLab CLI
        "glow",            # Render markdown in CLI
        "helix",           # Alternative neovim
        "httpie",          # HTTP client
        "yq",
        "eza",
        "neovim",
        "tmux",
        "pet",
        "docker",
        "usbutils",        # check fingerprint info
        "fprintd",         # fingerprint
        "entr",            # depdency for tmux-autoreload
        "tailscale",
        "tectonic",
        "hurl",            # runs HTTP requests defined in a simple plain text format.
        "vivid",           # Color generator for LS_COLORS env variable
        "espanso-wayland",
      ]
    [packages.pacman.homelab_member]
      packages = ["iperf"]
    [packages.pacman.personal_computer]
      packages = []


  [packages.python]
    to_remove = []
    [packages.python.common]
      packages = ["halper", "pygments"]
    [packages.python.dev_computer]
      packages = ["ansible-core", "cookiecutter"]
    [packages.python.homelab_member]
      packages = []
    [packages.python.personal_computer]
      packages = ["vid-cleaner"]
