[packages]
  [packages.python]
    to_remove = []

    [packages.python.common]
      packages = [
        # CLI / Text Rendering
        "halper",
        "pygments",
      ]

    [packages.python.development]
      packages = [
        # Automation & Infra
        "ansible-core",
        "cookiecutter",

        # Git Workflow
        "commitizen",
        "pre-commit",

        # Editor Integration
        "pynvim",
      ]

    [packages.python.homelab]
      packages = []

    [packages.python.personal]
      packages = [
        # Utility
        "smassh",

        # Media
        "vid-cleaner",
      ]

  [packages.cargo]
    to_remove = []

    [packages.cargo.common]
      packages = []

    [packages.cargo.development]
      packages = []

    [packages.cargo.homelab]
      packages = []

    [packages.cargo.personal]
      packages = [
        # Cargo Tooling
        "cargo-binstall",
        "cargo-update",

        # Version Control System
        "ghgrab", # A TUI to download files/folders from repositories without cloning repos.
        "koji",   # conventional commit cli alternative for commitizen
        "oyui",   # Modern TUI merge tool and interactive diff editor for Jujutsu (jj) and Git
        # "starship-jj", # https://gitlab.com/lanastara_foss/starship-jj

        # LSP, formatter & linters

        # @lua
        "stylua", # Lua formatter

        # @markdown
        "rumdl", # performance markdown linter

        # @text
        "typos-cli",

        # Utility
        "cargo-seek",

        # Git & Version Control
        "gitlogue",
      ]

  [packages.node]
    to_remove = []

    [packages.node.common]
      packages = []

    [packages.node.development]
      packages = [
        # Task Runner
        "@go-task/cli", # modern makefile alternative - https://taskfile.dev/

        # Editor Integration
        "neovim",
      ]

    [packages.node.homelab]
      packages = []

    [packages.node.personal]
      packages = [
        # AI / Developer Tools
        "@openai/codex",

        # Git Workflow
        "opencommit",
      ]

[[runtimes]]
  features = ["development", "personal"]
  name     = "node"
  version  = "latest"

[[runtimes]]
  features = ["development"]
  name     = "go"
  version  = "latest"

[[runtimes]]
  features = ["development", "personal"]
  name     = "rust"
  version  = "latest"

[[runtimes]]
  features = ["development"]
  name     = "bun"
  version  = "latest"

[[runtimes]]
  features = ["development"]
  name     = "deno"
  version  = "latest"

[[runtimes]]
  features = ["development"]
  name     = "taplo"
  version  = "latest"
