[remote_servers]
  [remote_servers.ghcny]
    add_to_ssh_config        = true
    generate_public_key_only = true
    name                     = "ghcny"
    op_id                    = "5b2sfyzvwpuzcjcp2wfa7ablk4"
    tailscale_ip             = false

  [remote_servers.glcny]
    add_to_ssh_config        = true
    generate_public_key_only = true
    name                     = "glcny"
    op_id                    = "nhczmzrx5uazmizwj6yzkjqohi"
    tailscale_ip             = false

  [remote_servers.gcp1]
    add_to_ssh_config        = true
    generate_public_key_only = true
    name                     = "gcp1"
    op_id                    = "cidpjacci3fjd65sj2ffuhcd3i"
    tailscale_ip             = false

  [remote_servers.ghphyne]
    add_to_ssh_config        = true
    generate_public_key_only = true
    name                     = "ghphyne"
    op_id                    = "fzv7mncqpjjmezf47kloo4t6ji"
    tailscale_ip             = false

  [remote_servers.acer]
    add_to_ssh_config        = true
    generate_public_key_only = true
    name                     = "acer"
    op_id                    = "h4zlfpcdlr3r64qjteoqwww6be"
    tailscale_ip             = true

  [remote_servers.mbp]
    add_to_ssh_config        = true
    generate_public_key_only = true
    name                     = "mbp"
    op_id                    = "o3hurjw4rkl24c4msn22pzoele"
    tailscale_ip             = true
