[shell_env]
  [shell_env.xdg]
    cache_home        = "$HOME/.cache"
    config_home       = "$HOME/.config"
    data_dirs_default = "/usr/local/share:/usr/share"
    data_home         = "$HOME/.local/share"
    state_home        = "$HOME/.local/state"

  [shell_env.homebrew]
    bin_paths = ["/opt/homebrew/bin", "/opt/homebrew/sbin"]
    cellar = "/opt/homebrew/Cellar"
    fish_completions = [
      "/opt/homebrew/share/fish/completions",
      "/opt/homebrew/share/fish/vendor_completions.d",
    ]
    info_path = "/opt/homebrew/share/info"
    prefix = "/opt/homebrew"
    repository = "/opt/homebrew"

  [shell_env.common]
    EDITOR                = "nvim"
    GIT_CONFIG_GLOBAL     = "$XDG_CONFIG_HOME/git/config"
    LESSHISTFILE          = "/tmp/less-hist"
    LM_STUDIO_BIN         = "$HOME/.lmstudio/bin"
    PARALLEL_HOME         = "$XDG_CONFIG_HOME/parallel"
    PI_CODING_AGENT_DIR   = "$XDG_CONFIG_HOME/pi"
    PROTO_HOME            = "$XDG_CONFIG_HOME/proto"
    PYTHON_HISTORY        = "$XDG_STATE_HOME/python_history"
    SCREENRC              = "$XDG_CONFIG_HOME/screen/screenrc"
    STARSHIP_CONFIG       = "$XDG_CONFIG_HOME/starship/starship.toml"
    TMUXIFIER_LAYOUT_PATH = "$HOME/.config/tmuxifier/layouts"
    WGETRC                = "$XDG_CONFIG_HOME/wgetrc"
    _ZO_DATA_DIR          = "$XDG_DATA_HOME/zoxide"

  [shell_env.arch_linux]
    HYPRLAND_CONFIG = "$XDG_DATA_HOME/hypr/hyprland.conf"
    TERMINFO        = "$XDG_DATA_HOME/terminfo"
    TERMINFO_DIRS   = "$XDG_DATA_HOME/terminfo:/usr/share/terminfo"

  [shell_env.ssh_auth_sock]
    darwin = "$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    linux  = "$HOME/.1password/agent.sock"

  [shell_env.path]
    entries = [
      "/opt/homebrew/bin",
      "/opt/homebrew/sbin",
      "/opt/zerobrew/prefix/bin",
      "/bin",
      "/usr/bin",
      "/usr/sbin",
      "/sbin",
      "/usr/local/bin",
      "$HOME/go/bin",
      "$HOME/.cargo/bin",
      "$XDG_DATA_HOME/cargo/bin",
      "$HOME/.local/bin",
      "$HOME/bin",
      "/usr/bin/snap",
      "$PROTO_HOME/shims",
      "$PROTO_HOME/bin",
      "$HOME/.atuin/bin",
      "$XDG_CACHE_HOME/.bun/bin",
      "$HOME/.tmuxifier/bin",
      "$LM_STUDIO_BIN",
      "/run/current-system/sw/bin",
      "$HOME/.local/state/nix/profiles/profile/bin",
      "$HOME/.nix-profile/bin",
    ]
