[formatting]
  align_comments = true
  align_entries  = true
  indent_entries = true
  indent_tables  = true
  reorder_arrays = true # Be caution with reorder_arrays
  reorder_keys   = true

[[rule]]
  exclude = ["~/.local/share/chezmoi/chezmoi/dot_config/pet/config.toml"]

  # Reorder arrays for pet config file will make pet cli doesn't work
  # Because cmd = ["sh", "-c"] will formatted to  cmd = ["-c", "sh"]
  # It's wrong format because pet will run shell command "sh -c" which is flag is on the end, not in the beginning
  [rule.formatting]
    reorder_arrays = false
