[app]
overall = { bg = "#181616" }

[mgr]
cwd = { fg = "#c4b28a", bold = true }
hovered = { fg = "#c5c9c5", bg = "#223249", bold = true }
find_keyword = { fg = "#b6927b", bg = "#0d0c0c", bold = true }
find_position = { fg = "#8ea4a2", bg = "#0d0c0c", bold = true }
marker_marked = { fg = "#8a9a7b", bg = "#8a9a7b" }
marker_selected = { fg = "#c4b28a", bg = "#c4b28a" }
marker_copied = { fg = "#8ba4b0", bg = "#8ba4b0" }
marker_cut = { fg = "#E82424", bg = "#E82424" }
count_selected = { fg = "#181616", bg = "#c4b28a" }
count_copied = { fg = "#181616", bg = "#8ba4b0" }
count_cut = { fg = "#181616", bg = "#E82424" }
border_symbol = "│"
border_style = { fg = "#393836" }

[tabs]
active = { fg = "#181616", bg = "#c4b28a", bold = true }
inactive = { fg = "#737c73", bg = "#0d0c0c" }

[mode]
normal_main = { fg = "#181616", bg = "#c4b28a", bold = true }
normal_alt = { fg = "#c4b28a", bg = "#0d0c0c" }
select_main = { fg = "#181616", bg = "#8ea4a2", bold = true }
select_alt = { fg = "#8ea4a2", bg = "#0d0c0c" }
unset_main = { fg = "#181616", bg = "#E82424", bold = true }
unset_alt = { fg = "#E82424", bg = "#0d0c0c" }

[status]
perm_sep = { fg = "#658594" }
perm_type = { fg = "#c4b28a" }
perm_read = { fg = "#8a9a7b" }
perm_write = { fg = "#c4b28a" }
perm_exec = { fg = "#8ea4a2" }
progress_label = { fg = "#c4b28a", bold = true }
progress_normal = { fg = "#8a9a7b", bg = "#223249" }
progress_error = { fg = "#E82424", bg = "#223249" }

[which]
mask = { bg = "#0d0c0c" }
cand = { fg = "#c4b28a" }
rest = { fg = "#737c73" }
desc = { fg = "#C8C093" }
separator_style = { fg = "#658594" }

[confirm]
border = { fg = "#c4b28a" }
title = { fg = "#c4b28a", bold = true }
content = { fg = "#c5c9c5" }
btn_yes = { fg = "#181616", bg = "#8a9a7b", bold = true }
btn_no = { fg = "#E82424", bold = true }

[input]
border = { fg = "#c4b28a" }
title = { fg = "#c4b28a" }
value = { fg = "#c5c9c5" }
selected = { reversed = true }

[help]
on = { fg = "#8ea4a2" }
run = { fg = "#b6927b" }
desc = { fg = "#C8C093" }
footer = { fg = "#181616", bg = "#c4b28a" }

[filetype]
rules = [
  { mime = "inode/directory", fg = "#8ba4b0", bold = true },
  { mime = "image/*", fg = "#8ea4a2" },
  { mime = "{audio,video}/*", fg = "#b6927b" },
  { url = "*.{txt,md,rst,csv,*json*,toml,yml,yaml,xml,html,ini,cfg,conf,log}", fg = "#c5c9c5" },
  { url = "*", fg = "#C8C093" },
  { url = "*/", fg = "#8ba4b0", bold = true },
]

[icon]
dirs = [{ name = "*", text = "󰉋", fg = "#8ba4b0" }]
