base = "ocean"
syntax = "base16-ocean.dark"

[ui]
content_bg = "#1F1F28"
toc_accent = "#E6C384"
toc_bg = "#16161D"
toc_fg = "#C8C093"
toc_border = "#363646"
status_bg = "#16161D"
status_fg = "#C8C093"
status_brand_fg = "#E6C384"
status_brand_bg = "#2D4F67"
search_highlight_bg = "#E6C384"
search_match_bg = "#2D4F67"
code_gutter = "#54546D"

[markdown]
text = "#DCD7BA"
heading_1 = "#E6C384"
heading_2 = "#FF9E3B"
heading_3 = "#7AA89F"
heading_4 = "#C8C093"
heading_other = "#727169"
heading_underline = "#363646"
strong_text = "#DCD7BA"
link_text = "#7E9CD8"
link_hover = "#7FB4CA"
blockquote_text = "#C8C093"
blockquote_marker = "#E6C384"
inline_code_fg = "#98BB6C"
inline_code_bg = "#2A2A37"
rule = "#658594"
list_level_1 = "#E6C384"
list_level_2 = "#7AA89F"
list_level_3 = "#727169"
table_border = "#363646"
table_separator = "#658594"
table_header = "#E6C384"
table_cell = "#DCD7BA"
