base = "ocean"
syntax = "base16-ocean.dark"

[ui]
content_bg = "#181616"
toc_accent = "#c4b28a"
toc_bg = "#0d0c0c"
toc_fg = "#C8C093"
toc_border = "#393836"
status_bg = "#0d0c0c"
status_fg = "#C8C093"
status_brand_fg = "#c4b28a"
status_brand_bg = "#223249"
search_highlight_bg = "#c4b28a"
search_match_bg = "#223249"
code_gutter = "#625e5a"

[markdown]
text = "#c5c9c5"
heading_1 = "#c4b28a"
heading_2 = "#b6927b"
heading_3 = "#8ea4a2"
heading_4 = "#C8C093"
heading_other = "#727169"
heading_underline = "#363646"
strong_text = "#c5c9c5"
link_text = "#8ba4b0"
link_hover = "#7FB4CA"
blockquote_text = "#C8C093"
blockquote_marker = "#c4b28a"
inline_code_fg = "#8a9a7b"
inline_code_bg = "#1D1C19"
rule = "#658594"
list_level_1 = "#c4b28a"
list_level_2 = "#8ea4a2"
list_level_3 = "#727169"
table_border = "#393836"
table_separator = "#658594"
table_header = "#c4b28a"
table_cell = "#c5c9c5"
