base = "ocean"
syntax = "base16-ocean.dark"

[ui]
content_bg = "#101010"
toc_accent = "#FFC799"
toc_bg = "#161616"
toc_fg = "#A0A0A0"
toc_border = "#282828"
status_bg = "#161616"
status_fg = "#A0A0A0"
status_brand_fg = "#FFC799"
status_brand_bg = "#232323"
search_highlight_bg = "#FFC799"
search_match_bg = "#232323"
code_gutter = "#505050"

[markdown]
text = "#FFFFFF"
heading_1 = "#FFC799"
heading_2 = "#FFCFA8"
heading_3 = "#99FFE4"
heading_4 = "#A0A0A0"
heading_other = "#A0A0A0"
heading_underline = "#282828"
strong_text = "#FFFFFF"
link_text = "#99FFE4"
link_hover = "#FFCFA8"
blockquote_text = "#A0A0A0"
blockquote_marker = "#FFC799"
inline_code_fg = "#99FFE4"
inline_code_bg = "#1C1C1C"
rule = "#65737E"
list_level_1 = "#FFC799"
list_level_2 = "#99FFE4"
list_level_3 = "#A0A0A0"
table_border = "#282828"
table_separator = "#65737E"
table_header = "#FFC799"
table_cell = "#FFFFFF"
