[[Snippets]]
Description = "Apply"
Output = ""
Tag = ["chezmoi"]
command = 'chezmoi apply'

[[Snippets]]
Description = "Edit | and apply"
Output = ""
Tag = ["chezmoi"]
command = 'chezmoi edit --apply'

[[Snippets]]
Description = "Init "
Output = ""
Tag = ["chezmoi"]
command = 'chezmoi init --apply --prompt'

[[Snippets]]
Description = "Diff"
Output = ""
Tag = ["chezmoi"]
command = 'chezmoi diff'

[[Snippets]]
Description = "Forget | Only delete in the source directory"
Output = ""
Tag = ["chezmoi"]
command = 'chezmoi forget <path-to-target-file>'

[[Snippets]]
Description = "Destroy | Delete file between in source directory and target directory"
Output = ""
Tag = ["chezmoi"]
command = 'chezmoi destroy <path-to-target-file>'

[[Snippets]]
Description = "Melihat perbedaan"
