# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
# CUSTOM CONFIG
# ---------------------------------
format      = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$nodejs\
$bun\
$nix_shell\
$fill\
$line_break\
$character"""

# $time\

# [custom.jj]
#   command        = "prompt"
#   format         = "$output"
#   ignore_timeout = true
#   shell          = ["starship-jj", "--ignore-working-copy", "starship"]
#   use_stdin      = false
#   when           = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
	error_symbol   = "[➜](bold red)"
	success_symbol = "[➜](bold green)"

[time]
	disabled        = false
	format          = "[$time]($style) "
	style           = "bold gray"
	time_format     = "%T"                # 24 Hour format HH:mm:ss
	use_12hr        = false
	utc_time_offset = "+7"                # Timezone

[fill]
	symbol = " "

[jobs]
	format           = "[$symbol]($style)"
	number_threshold = 1
	style            = "bold red"
	symbol           = ""

[git_state]
	format = '\([$state( $progress_current/$progress_total)]($style)\) '
	style  = "bright-black"

[git_metrics]
	disabled = false  # Git metrics, example +21 -8

[cmd_duration]
	format = "[$duration]($style)"
	style  = "yellow"

[custom.stunnel]
	command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
	format  = "[TUNNEL OPEN for $output]($style)"
	style   = "red"
	when    = "ps aux | grep stunnel | grep -v grep"

	# ---------------------------------
	# CUSTOM CONFIG

# Disable the package module, hiding it from the prompt completely
[package]
	disabled = true
	symbol   = "󰏗 "

[aws]
	symbol = "  "

[buf]
	symbol = " "

[c]
	symbol = " "

[conda]
	symbol = " "

[crystal]
	symbol = " "

[dart]
	symbol = " "

[directory]
	read_only = " 󰌾"

[docker_context]
	symbol = " "

[elixir]
	symbol = " "

[elm]
	symbol = " "

[fennel]
	symbol = " "

[fossil_branch]
	symbol = " "

[git_branch]
	symbol = " "

[golang]
	symbol = " "

[guix_shell]
	symbol = " "

[haskell]
	symbol = " "

[haxe]
	symbol = " "

[hg_branch]
	symbol = " "

[hostname]
	disabled   = false
	format     = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
	ssh_only   = true
	ssh_symbol = "🌏 "

[java]
	symbol = " "

[julia]
	symbol = " "

[kotlin]
	symbol = " "

[lua]
	symbol = " "

[memory_usage]
	symbol = "󰍛 "

[meson]
	symbol = "󰔷 "

[nim]
	symbol = "󰆥 "

[nix_shell]
	symbol = " "

[nodejs]
	symbol = " "

[bun]
	format = "via [🍔 $version](bold green) "

[ocaml]
	symbol = " "

[os.symbols]
	AlmaLinux        = " "
	Alpaquita        = " "
	Alpine           = " "
	Amazon           = " "
	Android          = " "
	Arch             = " "
	Artix            = " "
	CentOS           = " "
	Debian           = " "
	DragonFly        = " "
	Emscripten       = " "
	EndeavourOS      = " "
	Fedora           = " "
	FreeBSD          = " "
	Garuda           = "󰛓 "
	Gentoo           = " "
	HardenedBSD      = "󰞌 "
	Illumos          = "󰈸 "
	Kali             = " "
	Linux            = " "
	Mabox            = " "
	Macos            = " "
	Manjaro          = " "
	Mariner          = " "
	MidnightBSD      = " "
	Mint             = " "
	NetBSD           = " "
	NixOS            = " "
	OpenBSD          = "󰈺 "
	OracleLinux      = "󰌷 "
	Pop              = " "
	Raspbian         = " "
	RedHatEnterprise = " "
	Redhat           = " "
	Redox            = "󰀘 "
	RockyLinux       = " "
	SUSE             = " "
	Solus            = "󰠳 "
	Ubuntu           = " "
	Unknown          = " "
	Void             = " "
	Windows          = "󰍲 "
	openSUSE         = " "

[perl]
	symbol = " "

[php]
	symbol = " "

[pijul_channel]
	symbol = " "

[python]
	symbol = " "

[rlang]
	symbol = "󰟔 "

[ruby]
	symbol = " "

[rust]
	symbol = " "

[scala]
	symbol = " "

[swift]
	symbol = " "

[zig]
	symbol = " "
