[mgr]
ratio = [1, 3, 5]
sort_by = "mtime"   # sort by last modified time
sort_reverse = true
show_hidden = false
linemode = "mtime"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
