[[Snippets]]
Description = "Update remote url to use SSH"
Output = ""
Tag = ["git"]
command = 'git remote set-url <alias=origin> <host=git@github.com>:<username/workplace=|_chianyungcode_||_seraphynee_|>/<repo>.git'

[[Snippets]]
Description = "Clone repository with SSH"
Output = ""
Tag = ["git"]
command = 'git clone <host=git@github.com>:<username/workplace>/<repo>.git'

[[Snippets]]
Description = "Check local branch connect to which remote branch"
Output = ""
Tag = ["git"]
command = 'git branch -vv'

[[Snippets]]
Description = "List all branch in local and remote"
Output = ""
Tag = ["git"]
command = 'git branch --all'
