[[Snippets]]
  Description = "Apply"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi apply'

[[Snippets]]
  Description = "Edit | and apply"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi edit --apply'

[[Snippets]]
  Description = "Init "
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi init --apply --prompt'

[[Snippets]]
  Description = "Diff"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi diff'

[[Snippets]]
  Description = "Forget | Only delete in the source directory"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi forget <path-to-target-file>'

[[Snippets]]
  Description = "Destroy | Delete file between in source directory and target directory"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi destroy <path-to-target-file>'

[[Snippets]]
  Description = "Force refresh download external"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi --refresh-externals apply'

[[Snippets]]
  Description = "Clear the state of run_onchange_ scripts"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi state delete-bucket --bucket=entryState'

[[Snippets]]
  Description = "Clear the state of run_once_ scripts"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi state delete-bucket --bucket=scriptState'

[[Snippets]]
  Description = "Apply all file only in maximum 1 above parent directory"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi apply --parent-dirs <path-to-target-file/directory>'

[[Snippets]]
  Description = "Copy target path"
  Output      = ""
  Tag         = ["chezmoi"]
  command     = 'chezmoi target-path <paste_current_buffer_neovim> | pbcopy'
